# Generated by Django 5.1.4 on 2025-01-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('director_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie_app.director')),
            ],
            bases=('movie_app.director',),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '*'), (2, '* *'), (3, '* * *'), (4, '* * * *'), (5, '* * * * *')], default=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='search_words',
            field=models.ManyToManyField(blank=True, to='movie_app.searchword'),
        ),
    ]
