# Generated by Django 5.1.4 on 2025-01-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_searchword_alter_review_stars_movie_search_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='name',
        ),
        migrations.AddField(
            model_name='director',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
